import fs from "fs/promises";
import {
  Asset,
  BASE_FEE,
  Horizon,
  Keypair,
  Networks,
  Operation,
  TransactionBuilder,
} from "@stellar/stellar-sdk";

const USDC_ISSUER =
  "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5";
const horizon = new Horizon.Server("https://horizon-testnet.stellar.org");

async function friendbot(addr) {
  const res = await fetch(`https://friendbot.stellar.org?addr=${addr}`);
  if (!res.ok) {
    throw new Error(`Friendbot failed for ${addr}: ${res.status}`);
  }
}

async function addTrustline(kp) {
  const acc = await horizon.loadAccount(kp.publicKey());
  const tx = new TransactionBuilder(acc, {
    fee: BASE_FEE,
    networkPassphrase: Networks.TESTNET,
  })
    .addOperation(
      Operation.changeTrust({
        asset: new Asset("USDC", USDC_ISSUER),
      }),
    )
    .setTimeout(60)
    .build();
  tx.sign(kp);
  return horizon.submitTransaction(tx);
}

const recipient = Keypair.random();
const payer = Keypair.random();

console.log("Funding accounts via Friendbot…");
await Promise.all([
  friendbot(recipient.publicKey()),
  friendbot(payer.publicKey()),
]);
await new Promise((r) => setTimeout(r, 2000));

console.log("Adding USDC trustlines…");
await Promise.all([addTrustline(recipient), addTrustline(payer)]);

const env = `# Generated by scripts/setup.mjs — complete manual steps in README
STELLAR_NETWORK=stellar:testnet
STELLAR_RECIPIENT=${recipient.publicKey()}
STELLAR_SECRET_KEY=${payer.secret()}
REFLECTOR_PUBLIC_KEY=${payer.publicKey()}
OZ_API_KEY=

FACILITATOR_URL=https://channels.openzeppelin.com/x402/testnet
REFLECTOR_RPC_URL=https://soroban-testnet.stellar.org
REFLECTOR_PULSE_CONTRACT_ID=CCYOZJCOPG34LLQQ7N24YXBM7LL62R7ONMZ3G6WZAAYPB5OYKOMJRN63
NEXT_PUBLIC_APP_URL=http://localhost:3000
`;

await fs.writeFile(".env.local", env);

console.log("\nWrote .env.local");
console.log(`\nFund payer with testnet USDC:`);
console.log(`  https://faucet.circle.com  →  ${payer.publicKey()}`);
console.log(`\nOZ Channels testnet API key:`);
console.log(`  https://channels.openzeppelin.com/testnet/gen  →  OZ_API_KEY`);
